version: '1'

volumes:
    mysql_data:
        driver: local

services:
    users_api:
        build: .
        container_name: api
        env_file: .env.docker
        command: >
            gunicorn -b 0.0.0.0:5000
            -k gevent
            -w 4
            --chdir /app
            --access-logfile -
            --reload
            app:app
        ports:
            - "5000:5000"
        volumes:
            - .:/app

    db:
        image: mysql
        command: sh -c "echo '
            CREATE DATABASE IF NOT EXISTS users;
            CREATE DATABASE IF NOT EXISTS users_test;
            ' > /docker-entrypoint-initdb.d/init.sql;
            /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=
            "
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'very_secure_password'
        expose:
            - "3306"
        ports:
            - "32769:3306"
        depends_on:
            - users_api